CREATE TABLE CONTACT_INFORMATION  (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	firstName VARCHAR(100),
	lastName VARCHAR(100),
	phone VARCHAR(100),
	email VARCHAR(100),
	address VARCHAR(100),
	zip VARCHAR(100),
	city VARCHAR(100),
	country VARCHAR(100)
) ;

CREATE TABLE BIOBANK  (
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	acronym VARCHAR(100),
	name VARCHAR(100),
	url VARCHAR(100),
	juristicPerson VARCHAR(100),
	country VARCHAR(100),
	description VARCHAR(100),
	CONSTRAINT biobankcontactInfo FOREIGN KEY (id)
	REFERENCES CONTACT_INFORMATION(id)
) ;

CREATE TABLE SAMPLE_COLLECTION  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	ACRONYM VARCHAR(100),
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(800),
	SEX VARCHAR(100),
	AGE_LOW VARCHAR(100),
	AGE_HIGH VARCHAR(100),
	AGE_UNIT VARCHAR(100),
	DATA_CATEGORY VARCHAR(800),
	COLLECTION_TYPE VARCHAR(100),
	DISEASES VARCHAR(2000),
	CONSTRAINT CONTACT_INFORMATION_FK FOREIGN KEY (ID)
	REFERENCES CONTACT_INFORMATION(ID)
) ;

CREATE TABLE STUDY  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	STUDY_DESIGN VARCHAR(100),
	SEX VARCHAR(100),
	AGE_LOW VARCHAR(100),
	AGE_HIGH VARCHAR(100),
	AGE_UNIT VARCHAR(100),
	DATA_CATEGORY VARCHAR(100),
	TOTAL_NUMBER_OF_PARTICIPANTS VARCHAR(100),
	TOTAL_NUMBER_OF_DONORS VARCHAR(100),
	INCLUSION_CRITERIA VARCHAR(100),
	CONSTRAINT CONTACT_INFORMATION FOREIGN KEY (ID) REFERENCES CONTACT_INFORMATION(ID),
	CONSTRAINT PRINCIPAL_INVESTIGATOR FOREIGN KEY (ID) REFERENCES CONTACT_INFORMATION(ID)
) ;

CREATE TABLE SAMPLE  (
	ID VARCHAR(100) NOT NULL PRIMARY KEY,
	PARENT_SAMPLE_ID VARCHAR(100),
	MATERIAL_TYPE VARCHAR(800),
	STORAGE_TEMPERATURE VARCHAR(100),
	SAMPLED_TIME VARCHAR(100),
	ANATOMICAL_SITE VARCHAR(800),
	CONSTRAINT BIOBANK_FK FOREIGN KEY (ID) REFERENCES BIOBANK(ID),
	CONSTRAINT SAMPLE_COLLECTION_FK FOREIGN KEY (ID) REFERENCES SAMPLE_COLLECTION(ID),
	CONSTRAINT STUDY_FK FOREIGN KEY (ID) REFERENCES STUDY(ID)
) ;